### ISSUE TITLE
Integrating HUSH3 dpow

### ISSUE THREAD

**Issue by kolobus** [KomodoPlatform/NotaryNodes#382]
Hello.

Please use this thread as an example of integrating coin into Komodo dpow network.

Current HUSH3 state is not ready. They need to code in 3p dpow keys.
Awaiting response here.

@DeckerSU @ca333 @leto

**Comment by leto** [comment]
@DeckerSU @ca333 this is being worked on in the `duke` branch which has merged in all relevant updates and fixes from KMD 0.5.0 release, with Hush changes. This will soon be merged to the Hush `dev` branch for a round of testing before being sent to KMD notaries for testing. We try very hard to find bugs before notaries find them.

If you have any suggestions for how you tested the hardfork code in KMD, to simulate enabling the new season, that would be helpful. I plan to do a basic test where I change the hard fork block height and verify my node can pass thru that height and still operate normally, making p2p connections and answering RPCs, even if it does go on a chainfork. A more advanced integration test with iguana is likely the next step after that.

**Comment by ca333** [comment]
We did it basically the same way - isolated a small test-net and set a "test-hardfork-height" to simulate it.

**Comment by leto** [comment]
I am currently testing a CLI argument that can over-ride the fork height, for my own testing and also to make things as easy as possible for NN's to test/simulate

**Comment by leto** [comment]
@kolobus @ca333 @DeckerSU https://github.com/KomodoPlatform/dPoW/issues/20

We have about 2 weeks to go, anything I can help with?

**Comment by ca333** [comment]
All good and almost set for the big day - we ll keep you updated on the NN upgrade process.  Thanks for the ping.

**Comment by TheComputerGenie** [comment]
Can this be closed?

**Comment by kolobus** [comment]
Should be closed I assume.
