### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by gafty** [KomodoPlatform/NotaryNodes#516]
About Me

I'm a Linux systems administrator with around 18 years of experience.
In my early career, I was one of the first Internet Service Providers in my neighborhood in Bucharest/Romania.
After years and a lot of nice experiences working in my own ISP Business, in 2015 i bought my first 4 BTC (Thanks to my actual wife for the support ;).
Since then, I studied a lot about Bitcoin, Blockchain, and I foused on a few of those bleeding edge technologies and projects like Komodo.
Komodo is/was one of my favorite projects.I also like solid projects like SKY (Skycoin), LBTC (BTC Lightning Network), FXC (Flexacoin), ETC (Ethereum Classic), EOS, Steem, Golem or DOGE ;) .
I also mined ethereum with a few rigs since it was quoted around 2-5 USD.
Now, I use some trading bots on diffrent CEX and some DEX markets or investment platforms like the romanian project venbot.io . 

Server specifications

Region: EU
2 x Intel(R) Xeon(R) CPU E5-2670
256 GB RAM
2 x 2 TB SSD
2 x 500 mbit/s (on diffrent ISPs)
Location: Romania

Send your VOTE2020 tokens to: RHhqzvWutYuhoQyv2f8WUJv6yhCunjM9zH

Important dates for Season 4 NN elections

According to https://github.com/KomodoPlatform/dPoW/blob/master/doc/bible.md#guideline-general-infos-and-policies :

KMD snapshot on April 12th
autoelection announcement should be done on April 12th 12pm UTC
airdrop of VOTE2020 tokens should be done on April 13th 12pm UTC
elections should start on April 13th 12pm UTC and ends on Mai 4th 12pm UTC

Disclosure
I am NOT a part of the Komodo Team, so you can vote me as a "geek newbie" ;) \m/

Contact details
Discord: gafty#0963
Keybase: https://keybase.io/gafty
GitHub: https://github.com/gafty
Email: gafty@me.com

**Comment by kolobus** [comment]
Wrong place
